### ISSUE TITLE
Search bar not working properly

### ISSUE THREAD

**Issue by jhodges10** [dashpay/insight-ui#20]
If you paste in this address: XkbRp5aT5vGnYi7obCGvmX2FAQV34u6Dfw, it just continually tries to load something.

Looks like the problem is that it's attempting to parse an address as a block based on the API endpoint it's trying to hit.

`https://insight.dash.org/insight-api/block/XkbRp5aT5vGnYi7obCGvmX2FAQV34u6Dfw`

 ^^ Pulled from console error log

**Comment by nmarley** [comment]
Can re-produce, but it eventually was able to pull up the address page. But I agree that it's not ideal to first query for blocks & transactions and get a 404, esp. when we should be able to determine an address vs hash160 based on the string length & prefix bytes.

<img width="1616" alt="2018-06-18-insight-ui-bug1" src="https://user-images.githubusercontent.com/1735354/41561607-3b108186-72ff-11e8-8022-c7ff34af86ae.png">

**Comment by nmarley** [comment]
@jhodges10 This should be fixed now by https://github.com/dashevo/insight-api/pull/25
