### ISSUE TITLE
Verify message not working

### ISSUE THREAD

**Issue by Nutomic** [dashpay/insight-ui#51]
The network response from `https://insight.dash.org/insight-api/messages/verify` is `{"result": true}`, but the site just keeps displaying "Loading...". Apparently this is a Javascript error, the following is shown in the browser console (Firefox 68).

```
TypeError: "$http.post(...).success is not a function"
    verify https://insight.dash.org/insight/js/main.min.js:3
    Angular 7
        recurse
        e
        $eval
        $apply
        compile
        sg
        d
angularjs-all.min.js:3:57395
    Angular 6
        e
        get
        $apply
        compile
        sg
        d
```

**Comment by Alex-Werner** [comment]
Hi @Nutomic, 

Thank you for your issue, would you be so kind to provide a reproducible example (address,sig,msg) ? 
AFAIK there is no one maintainers anymore on this repo, it's a community owned one I guess. 
However, I would like to take a look this week-end. 
Also, you should be able to open the web console to display additionnal errors, did you find some with more info ? 
Especially something like `Possibly unhandled rejection: {errorDesc}`

**Comment by Nutomic** [comment]
Here you go:
Address: `XnicRaq2bGVLerZJzHPs36z9xRcjoKm4qg`
Signature: `Hxhw0WeS9RG606CvF6/w0k5aqgE44fCmt3PxOECT9CxNB/cAn32a/hfSMRL7NoDp24RoIZsd/NPixOdV5ldf14g=`
Message: `test`

I dont see an option to get additional errors in Firefox. Chromium gives this error message:
```
angularjs-all.min.js:3 TypeError: $http.post(...).success is not a function
    at b.$scope.verify (main.min.js:3)
    at angularjs-all.min.js:3
    at e (angularjs-all.min.js:3)
    at b.$eval (angularjs-all.min.js:3)
    at b.$apply (angularjs-all.min.js:3)
    at HTMLButtonElement.<anonymous> (angularjs-all.min.js:3)
    at sg (angularjs-all.min.js:3)
    at HTMLButtonElement.d (angularjs-all.min.js:3)
(anonymous) @ angularjs-all.min.js:3
(anonymous) @ angularjs-all.min.js:3
$apply @ angularjs-all.min.js:3
(anonymous) @ angularjs-all.min.js:3
sg @ angularjs-all.min.js:3
d @ angularjs-all.min.js:3
```

**Comment by bfoss765** [comment]
Added to backlog.

**Comment by Alex-Werner** [comment]
Hi @Nutomic,
Thank you again for your report, this has now been fixed and will go through review process. 
We will then try to ship that live soon :)
Closing this in favor of the PR for further discussions, but do not hesitate to reopen this issue again if your have more questions.

**Comment by Alex-Werner** [comment]
@Nutomic 
Thank you for you wait, we were quite overwhelmed by some urgent things that made this fix low priority, however, thank to your report, we were able to address this issue in the PR #53 
Which is now working. 
Thank you for your help and your tests vectors :D 

https://insight.dashevo.org/insight/messages/verify
![image](https://user-images.githubusercontent.com/5849920/68947818-b0361c80-07b6-11ea-8ef2-dfabe1ca2ae4.png)
