### ISSUE TITLE
https://insight.dash.org/insight/ 

### ISSUE THREAD

**Issue by YXinAndy** [dashpay/insight-ui#56]
Hello,https://insight.dash.org/insight/, this website no longer available?,

**Comment by Alex-Werner** [comment]
Hi @YXinAndy, 
Thank you for your report, 
We are aware of this issue and are active in the process of deploying a fix (should happen in the coming hours hopefully).

**Comment by Alex-Werner** [comment]
Hi again @YXinAndy, 
The issue should now be fixed with the deployment of a working insight cluster. Sorry about it. 
Closing this, please, do not hesitate to reopen if you encounter any issues.
