### ISSUE TITLE
Broadcast transaction not working on evonet

### ISSUE THREAD

**Issue by cloudwheels** [dashpay/insight-ui#57]
**recreate**

Attempt to broadcast raw hex tx using UI at http://devnet-evonet-28309188.us-west-2.elb.amazonaws.com:3001/insight/tx/send

Page says 'loading' and nothing happens...

**Comment by Alex-Werner** [comment]
Hey @cloudwheels , 
Thank you for this ! I have tested with 
`030000000162a750e78b4228e683c8fbaa81dcec5948e0ce03219dd9a5e9028f1ccd353828000000006a473044022051c5000c02e2bd398c102f5de36baa5ad21e9dbb1a085410b5ba3fa544c8785802204aaec39b9cf97e22fb0918be5f764a60885fda11c5f427c0353b03bdd7bc79630121021cf98c99f6df1a41452bdab4b3866613dc053e87372dd0cae8281e566826fc6effffffff0133aa9041000000001976a914b20e28d8d42e1b933ed8fbfb9af7737e4212895a88ac00000000` and able to reproduce. 

![image](https://user-images.githubusercontent.com/5849920/77130163-2396b600-6a57-11ea-8db8-f9777886b7e3.png)

It appears that it does work (see this : http://devnet-evonet-28309188.us-west-2.elb.amazonaws.com:3001/insight/tx/f62cba089714975c4964b85db157a1866a8cb1df156c344e5fd4dad75536974c) but that instead, some changes in angular rendered .success() broken. 
Theses have been changed for `.then`, culprit being here : https://github.com/dashevo/insight-ui/blob/master/public/src/js/controllers/transactions.js#L196, similarly, .error() is .catch().
