### ISSUE TITLE
Funds didnt get to the receiver

### ISSUE THREAD

**Issue by kenpachi615** [dashpay/insight-ui#64]
I used dash to transfer some funds but its been days now but still no funds added...i dont know how this will be handle but pls do handle it. Thanks

**Comment by antouhou** [comment]
Hi @kenpachi615! What service did you use to transfer the funds? Exchange? Wallet? Where you were supposed them? What's the recipient's address? What's the transaction id?

**Comment by kenpachi615** [comment]
Dash wallet is what i used. 
Transaction 195bd94d7c3241669b525ba7ae5b659a358a20611f784532f377798ce87aacd9

Recipient's address: XpmETwK3KrRmQTDNHhBY6QDzpaKQqu6mqz

![Screenshots_2020-11-07-08-41-20_(1)](https://user-images.githubusercontent.com/73934269/98444121-8ff12300-20d5-11eb-8b58-808db9139f9d.png)

**Comment by antouhou** [comment]
The funds reached `XpmETwK3KrRmQTDNHhBY6QDzpaKQqu6mqz` about a week ago. In fact the funds were spent from the recipient address in the transaction `51398efd80b1bc42f56cfa1bced10c9cb5da12ba883f3eb8de35e51c11a4cd2c` already. If it's an exchange account, then that's the problem on the exchange side. If that's the case, please consult the exchange support.

Thank you!

**Comment by kenpachi615** [comment]
Wow....thats crazy. 

Thanks
